### ISSUE TITLE
Transition to different bgm

### ISSUE THREAD

**Issue by iles-stell** [East-Antarctic-Atlantis-model/initial_conditions#10]
Hello,
I've been figuring out why the 29 polygon model is having troubles working, past the sea_ice.nc file.

I have been adapting the initial conditions code to add a box using _shinyrAtlantis_ functions. While doing that, it occurred to me that the number of boxes and the bgm file name are not changed to 29 in the final nc file. The issue in summary:
-  If I use the 29_polygon.bgm, then the loop to `"## Iterate through each row of 'template.h' to match and update values"` doesn't work (`Error in ``[<-.data.frame``(``*tmp*``, i, 2:ncol(template.h), value = c(NA,  :replacement has 28 items, need 29`) and I can't progress beyond that.
- However, the final nc file comes out with the wrong number of boxes and wrong geometry file.

Is there a workaround? Can I manually change dimensions and geometry name of the file before it's saved as an nc?

**Comment by jporobicg** [comment]
Did you create the new templates using the version with 29 polygons? If you use the old templates, you will have this issue.

**Comment by iles-stell** [comment]
Hello,
After trying a few different tricks, I figured that the nc file was getting saved with the entire filepath assigned to the variable bgm.file (e.g., if I set the bgm.file as 'source_files/EAAM_28_polygons_xy.bgm' then the geometry would be called source_files/EAAM_28_polygons_xy.bgm, leading to Atlantis not recognising the file).

Simple fix is to reassign bgm.file as just the name of bgm (bgm.file = 'EAAM_28_polygons_xy.bgm') just before the make.init.nc file. If the model runs I will close the thread and perhaps add a note in the appropriate repo!
Thank you 🤓

**Comment by iles-stell** [comment]
That worked! Will amend the code/add a note and close this thread 🎉

**Comment by jporobicg** [comment]
> Simple fix is to reassign bgm.file as just the name of bgm (bgm.file = 'EAAM_28_polygons_xy.bgm') just before the make.init.nc file. If the model runs I will close the thread and perhaps add a note in the appropriate repo! Thank you 🤓

Yes, that should be updated at the beginning of the code the bgm.file_28 should be bgm.file_29

**Comment by iles-stell** [comment]
Yep - I think I might've changed the code as I was playing around with it at the beginning. It was just the geometry's name being saved incorrectly (i.e., whole filepath instead of just the bgm name). All good now!
