### ISSUE TITLE
Box order not matching columns

### ISSUE THREAD

**Issue by iles-stell** [East-Antarctic-Atlantis-model/initial_conditions#5]
![image](https://github.com/East-Antarctic-Atlantis-model/initial_conditions/assets/85492378/dec73944-4d6e-41e8-93df-8c14b93c1597)

Box 0 is not aligned to correct column, leading to the last column box-less.

**Comment by iles-stell** [comment]
(the file is horiz_filled)

**Comment by jporobicg** [comment]
Fixed. added row.names = FALSE when writing the table
