### ISSUE TITLE
nc file returns empty

### ISSUE THREAD

**Issue by iles-stell** [East-Antarctic-Atlantis-model/initial_conditions#6]
Nc file is empty upon check after running through the initial conditions generation procedure

**Comment by jporobicg** [comment]
I'm able to create the init file without issues. try to run again with the updated version of the code.

**Comment by iles-stell** [comment]
Nc file seems to work when checking it with shinyrAtlantis and running it through Atlantis; something is wrong with ncdump versions! Closing the issue.
