### ISSUE TITLE
Missing ncvarid

### ISSUE THREAD

**Issue by iles-stell** [East-Antarctic-Atlantis-model/initial_conditions#7]
When running the model with the new initial conditions, I get the following error at t = 0:
ncvarid: ncid 458752: NetCDF: Variable not found

I tried to do some troubleshooting.
A comparison between variables from the old and new nc files reveals that some variables are missing from the new initial conditions file: Light_Adaptn_IPL and Light_Adaptn_IDF (both ice species) are not present in the new conditions (while XXX_F variables have been added for age-structured groups). Could this be the issue?

**Comment by iles-stell** [comment]
Issue probably due to shinyrAtlantis initGen.R, code lines 121-123:
    ## set up a flag for groups that need light adaptation
    light.adpn.grps <- c("DINOFLAG", "MICROPHTYBENTHOS", "SM_PHY",
                         "MED_PHY", "LG_PHY")

It is missing ICE_DIATOMS and ICE_MIXOTROPHS. Will work on it ASAP.

**Comment by iles-stell** [comment]
Added the functional groups to light.adapn.grps.
- No variables are missing when comparing the two nc files,
- Error still persists when using the new file to run Atlantis

**Comment by jporobicg** [comment]
> Issue probably due to shinyrAtlantis initGen.R, code lines 121-123: ## set up a flag for groups that need light adaptation light.adpn.grps <- c("DINOFLAG", "MICROPHTYBENTHOS", "SM_PHY", "MED_PHY", "LG_PHY")
> 
> It is missing ICE_DIATOMS and ICE_MIXOTROPHS. Will work on it ASAP.

Yes, that was a problem. I forgot to add them. thanks

**Comment by jporobicg** [comment]
@iles-stell fixed the problem by adding the missing code see https://github.com/East-Antarctic-Atlantis-model/initial_conditions/issues/7#issuecomment-1831027137
