### ISSUE TITLE
Mismatching/wrong init_filled values

### ISSUE THREAD

**Issue by iles-stell** [East-Antarctic-Atlantis-model/initial_conditions#8]
Tracer values are mismatched or incorrect in new init_file created by make.init.nc(). For example:

New values from EAAM_init_28_filled.csv
<img width="911" alt="image" src="https://github.com/East-Antarctic-Atlantis-model/initial_conditions/assets/85492378/1af937fe-92af-4f4c-8762-6deb09cd210a">

Values from old initial conditions file used as a source for filling in new values:
<img width="239" alt="image" src="https://github.com/East-Antarctic-Atlantis-model/initial_conditions/assets/85492378/e3320e7a-5125-4c65-914d-5df1dddc9715">

**Comment by jporobicg** [comment]
That value must be changed manually on the template to be reflected in the netcdf.
