### ISSUE TITLE
Nc file - invalid dimension ID or name

### ISSUE THREAD

**Issue by iles-stell** [East-Antarctic-Atlantis-model/initial_conditions#9]
When using the following files:
<img width="438" alt="image" src="https://github.com/East-Antarctic-Atlantis-model/initial_conditions/assets/85492378/61d98627-c6b6-4b9c-ad1d-2c9a21d8ad5c">
I get the error: **ncdimid: ncid 65536: NetCDF: Invalid dimension ID or name**.
Unfortunately I still can't open the nc file to check it - I am using the latest netcdf4 version (4.9.2).

**Comment by iles-stell** [comment]
Google search suggests that there might be inconsistencies with variable names or depth layers.
TO-DO: 

- [x] check that time is included!
- [x] check variable names
- [x] check variable value (e.g., manually input svel for ice_diatoms - see archived issue)
- [x] check that depth layers and boxes are correct value/match bgm

**Comment by iles-stell** [comment]
Possible issue: in the horiz_init.csv needed to build the nc file, XXX_N is not read in - instead, only XXX_F appears. Could it be that Nitrogen values are missing in the final nc?

TO-DO:

**not the issue!
- [x] edit + test code for creating horiz file:
default.val <- c(grep('*_StructN', orig.default$Variables), grep('*_ResN', orig.default$Variables), grep('*_F$', colnames(orig.m)))
required_vals <- c(grep('*_StructN', colnames(orig.m)), grep('*_ResN', colnames(orig.m)), grep('*_F$', colnames(orig.m)))
**

Try next:
in make.init.csv, properties that are labelled as "custom" in the init.csv (under the wc.hor.pattern column) are read in the horiz.csv file. XXX_N is not labelled as custom in the init.file, therefore it does not appear in the horiz.csv and causes issues with the final structure of the nc.
What to do? 
- [x] check that's the issue - manually change XXX_N to custom

**Comment by iles-stell** [comment]
After manually editing some values in the init_filled.csv, the nc file seems to be read by the model; however, Iron values might be wrong. In the "original" nc, iron (Micronut) had a specific value per box, while in the new nc it is labelled as constant, uniform, and does not appear in the horiz file.

**Comment by jporobicg** [comment]
> After manually editing some values in the init_filled.csv, the nc file seems to be read by the model; however, Iron values might be wrong. In the "original" nc, iron (Micronut) had a specific value per box, while in the new nc it is labelled as constant, uniform, and does not appear in the horiz file.

Good job! yes, Some of the variables and flags in the template need to be updated for the model to recognise the specific configuration of this particular model. Usually, I will leave a default value for some variables and leave Atlantis to deal with that as an emerging result of the internal dynamic of the system. Now, suppose you want to fine-tune the initial condition to represent some spatial difference in any variable. In that case, changing the labels from constant or uniform to custom is the way to go.

**Comment by iles-stell** [comment]
I think we're getting there... the model now opens the initial conditions file for 29 polygons and reads some information from it, but then spits out this error: "readBMphysData: dump 0 not in file (0 records)". I'll check whether I am using the right bgm file.

**Comment by iles-stell** [comment]
There might be an issue linked to the fact that the sea_ice.nc file has info on only 28 boxes. Will work on that and report back asap!
